version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get -y update
      - apt-get -y upgrade
      - apt -y upgrade gradle
      - echo $(java -version)
      - echo $(gradle -v)
  build:
    commands:
      - echo Entered the build phase...
      - ./gradle
      - ./gradlew jar
      - ./gradlew unitTest

artifacts:
  files:
    - build/libs/kafka-*.jar
  discard-paths: yes
